config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'index#index'
  resources :volumes
  resources :archives

  post '/search', to: 'index#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :volume
  belongs_to :user

  enum type_archive: [
    :video,
    :photo,
    :edit
  ]

  enum resolution: [
    %s{360p},
    %s{480p},
    %s{HD},
    %s{FULL HD}
  ]

  enum environment: [
    :any,
    :internal,
    :external
  ]


  validates :name, :size, :type_archive, :directory, :volume_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/volume.rb
class Volume < ApplicationRecord
  belongs_to :user
  has_many :archives

  enum type_volume: [
    :RAID,
    :HD,
    :FITA
  ]

  validates :name, :type_volume, :capacity, presence: true

  def get_capacity
    if (self.capacity / 1024 ) >= 1024
      return "#{self.capacity / 1024 / 1024} TB"
    end
    "#{self.capacity / 1024} Gb"
  end

  def space_available
    capacity - in_use
  end

  def in_use
    archives.sum(:size)
  end

  def get_icon
    if type_volume == 'RAID'
      return "fa fa-server"
    end
    return "fa fa-hdd"
  end

  def get_icon_medium
    "#{get_icon} fa-2x"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: [:show, :edit, :update, :destroy]

  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.all
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params)

    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, notice: 'Arquivo foi salvo com sucesso.' }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: 'Arquivo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, notice: 'Arquivo foi deletado com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params.require(:archive).permit(:name, :size, :tipe_archive, :resolution, :environment, :description, :directory, :volume_id, :inserted_in, :user_id)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @volumes = Volume.all
  end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  before_action :set_volume, only: [:show, :edit, :update, :destroy]

  # GET /volumes
  # GET /volumes.json
  def index
    @volume = Volume.new
    @volumes = Volume.all
  end

  # GET /volumes/1
  # GET /volumes/1.json
  def show
  end

  # GET /volumes/new
  def new
    @volume = Volume.new
  end

  # GET /volumes/1/edit
  def edit
  end

  # POST /volumes
  # POST /volumes.json
  def create
    @volume = Volume.new(volume_params)

    respond_to do |format|
      if @volume.save
        format.html { redirect_to @volume, notice: 'Volume criado com sucesso.' }
        format.json { render :show, status: :created, location: @volume }
      else
        format.html { render :new }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volumes/1
  # PATCH/PUT /volumes/1.json
  def update
    respond_to do |format|
      if @volume.update(volume_params)
        format.html { redirect_to @volume, notice: 'Volume atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @volume }
      else
        format.html { render :edit }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volumes/1
  # DELETE /volumes/1.json
  def destroy
    @volume.destroy
    respond_to do |format|
      format.html { redirect_to volumes_url, notice: 'Volume deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volume
      @volume = Volume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volume_params
      params.require(:volume).permit(:name, :type_volume, :capacity, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/archives/_form.html.erb
<%= simple_form_for @archive, :html => { :class => 'form form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :size, as: :string %>
  <%= f.input :type_archive, as: :select, collection: Archive.type_archives.keys %>
  <%= f.input :resolution %>
  <%= f.input :environment, as: :select, collection: Archive.environments.keys %>

  <%= f.input :directory %>
  <%= f.input :volume_id, as: :select, collection: Volume.all.map { | v | [v.name, v.id] } %>
  <%= f.input :inserted_in %>
  <div class="">
    <label for="" class="label-field">Decrição</label>
      <%= f.input :description, as: :text, label: false, input_html: {rows: 10}%>
  </div>
    <%= f.input :user_id, as: :hidden , input_html: { value: if @archive.user_id.nil? then current_user.id else @archive.user_id end} %>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                archives_path, :class => 'btn btn-default' %>
<% end %>

app/views/archives/_table_archives.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:type_archive) %></th>
      <th><%= model_class.human_attribute_name(:volume_id) %></th>
      <th><%= model_class.human_attribute_name(:inserted_in) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= link_to archive.name, archive_path(archive) %></td>
        <td><%= archive.type_archive %></td>
        <td><%= archive.volume_id %></td>
        <td><%= archive.inserted_in %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      archive_path(archive), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_archive_path(archive), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      archive_path(archive),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/archives/edit.html.erb
<%- model_class = Archive -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/archives/index.html.erb
<%- model_class = Archive -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= render 'table_archives',  model_class: model_class %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_archive_path,
            :class => 'btn btn-primary' %>

app/views/archives/new.html.erb
<%- model_class = Archive -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/archives/show.html.erb
<%- model_class = Archive -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @archive.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:size) %>:</strong></dt>
  <dd><%= @archive.size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_archive) %>:</strong></dt>
  <dd><%= @archive.type_archive %></dd>
  <dt><strong><%= model_class.human_attribute_name(:resolution) %>:</strong></dt>
  <dd><%= @archive.resolution %></dd>
  <dt><strong><%= model_class.human_attribute_name(:environment) %>:</strong></dt>
  <dd><%= @archive.environment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @archive.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:directory) %>:</strong></dt>
  <dd><%= @archive.directory %></dd>
  <dt><strong><%= model_class.human_attribute_name(:volume_id) %>:</strong></dt>
  <dd><%= @archive.volume_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:inserted_in) %>:</strong></dt>
  <dd><%= @archive.inserted_in %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              archives_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_archive_path(@archive), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              archive_path(@archive),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/index/index.html.erb
<div class="columns">
  <div class="column">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="media">
          <div class="media-left">
            <i class="fas fa-server fa-4x"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Volumes</h4>
            <span><%= Volume.count %> volumes cadastrados no sistema.</span>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <%= link_to "Cadastrar", new_volume_path, class: "btn btn-primary" %>
        <%= link_to "Ver todos", volumes_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>

  <div class="column ">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="media">
          <div class="media-left">
            <i class="fas fa-file fa-4x"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Arquivos</h2>
            <span><%= Archive.count %> arquivo cadastrados no sistema.</span>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <%= link_to "Cadastrar", new_archive_path,  class: "btn btn-primary" %>
        <%= link_to "Ver todos", archives_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>


</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Backups</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Arquivos", archives_path  %></li>
        <li><%= link_to "Volume", volumes_path  %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="">Olá, <strong><%=current_user.username%></strong>!</a></li>
          <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        <%end%>
        <!-- <li><%= link_to "Volume", volumes_path  %></li> -->
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="list-group sidebar-nav">
<%= link_to "Arquivos", archives_path, class: "list-group-item"  %>
  <%= link_to "Volume", volumes_path, class: "list-group-item"  %>
    <!-- <li><%= link_to "Link3", "/path3"  %></li> -->
  <div class="list-group-item">
    <h5>Pesquisa</h5>
    <!-- <hr>
    <form class="form form-vertical" action="<% search_path %>" method="post">
      <label for="">Nome</label><br>
      <input type="text" name="name" class="form-control" id="">
      <label for="">Tipo</label>
      <select class="form-control" name="">

      </select>

    </form> -->
  </div>
</div><!--/.well -->

app/views/layouts/_tabs.html.erb
<div class="tabs is-centered is-boxed is-medium">
  <ul>
    <li class="">
      <!-- <a>
        <span class="icon is-small"><i class="fas fa-image" aria-hidden="true"></i></span>
        <span>Pictures</span>
      </a> -->
      <%= link_to "Geral", root_path %>
    </li>
    <li>
      <%= link_to "Arquivos", archives_path %>
    </li>
    <li>
      <%= link_to "Volumes", volumes_path %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Backups" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">





    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render partial: 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-3">
        <%= render 'layouts/sidebar' %>
        </div><!--/span -->
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <!-- <footer>
        <p>&copy; Company 2018</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>

app/views/volumes/_form.html.erb
<%= simple_form_for @volume, :html => { :class => 'form-vertical' } do |f| %>
  <%if @volume.errors.any? %>
    <%@volume.errors.messages.each do | att, message | %>
      <div class="alert fade in alert-warning">
        <%= "#{@volume.class.human_attribute_name(att)} #{message[0]}" %>
      </div>
    <%end%>
  <%end%>
  <div class="row">
    <div class="col-sm-4">
      <div class="form-group">
        <%= f.input :name, class: "form-control", label: false, placeholder: "Nome" %>
      </div>

      <div class="form-group">
        <label for="">Tipo</label>
        <%= f.input :type_volume, as: :select, collection: Volume.type_volumes.keys, class: "form-control", label: false %>
      </div>

      <div class="form-group">
        <!-- <label for="">Capacidade</label> -->
        <%= f.input :capacity , class: "form-control", label: false, placeholder: "Capacidade" %>
      </div>
      <%= f.input :user_id, as: :hidden , input_html: { value: if @volume.user_id.nil? then current_user.id else @volume.user_id end} %>
    </div>




    <div class="col-sm-8">

      <%= f.text_area :description, cols: 60, rows: 10, placeholder: "Descrição" %>
    </div>
  </div>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                volumes_path, :class => 'btn btn-default' %>
<% end %>

app/views/volumes/edit.html.erb
<%- model_class = Volume -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/volumes/index.html.erb
<%- model_class = Volume -%>
<div class="page-header">
  <div class="row">
    <div class="col-sm-8"><h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>

    </div>
    <div class="col-sm-4">
      <br>
      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_volume_path,
                  :class => 'btn btn-primary' %>
    </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:type_volume) %></th>
      <th><%= model_class.human_attribute_name(:capacity) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @volumes.each do |volume| %>
      <tr>
        <td><%= link_to volume.name, volume_path(volume) %></td>
        <td><%= volume.type_volume %></td>
        <td><%= volume.in_use %> / <%= volume.get_capacity %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      volume_path(volume), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_volume_path(volume), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      volume_path(volume),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/volumes/new.html.erb
<%- model_class = Volume -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/volumes/show.html.erb
<%- model_class = Volume -%>
<div class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h1> <i class="<%= @volume.get_icon %>"></i> <%= @volume.name %></h1>
      </div>
      <div class="col-sm-4">
        <br>
        <%= link_to t('.back', :default => t("helpers.links.back")),
                      volumes_path, :class => 'btn btn-default'  %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_volume_path(@volume), :class => 'btn btn-default' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      volume_path(@volume),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

<dl class="dl-vertical">
  <dt>Espaço</dt>
  <dd><%= @volume.in_use%> de <%= @volume.capacity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_volume) %>:</strong></dt>
  <dd><%= @volume.type_volume %></dd>
  <hr>
  <dl class="">
    <dt>
      Arquivos
    </dt>
    <dd>
      <% if @volume.archives.any? %>
        <% render 'archives/table_archives', model_class: Archive %>
      <% else %>
        <p>Não há arquivos associados a esse volume no sistema.</p>
        <%= link_to "Cadastrar Arquivo",
                    new_archive_path,
                    :class => 'btn btn-primary' %>
      <% end %>
    </dd>
  </dl>
</dl>